[package]
name = "shuiqi"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1.0"
winit = "0.30.5"
async-trait = "0.1.82"
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }